import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Outfit } from "next/font/google";
import ChatbaseEmbed from "@/components/ChatbaseEmbed";

const outfit = Outfit({ subsets: ["latin"] });

// Define metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph: {
    title: "Create Next App",
    description: "Generated by create next app",
    type: "website",
    locale: "en_US",
    url: "https://your-domain.com",
  },
  twitter: {
    card: "summary_large_image",
    title: "Create Next App",
    description: "Generated by create next app",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={outfit.className}>
          <main>
            {children}
            <ChatbaseEmbed />
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}